test4/booktest/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(\d+)/(\d+)$',views.show, name='show'),
    url(r'^index2', views.index2, name='index2'),
    url(r'^user1', views.user1, name='user1'),
    url(r'^user2', views.user2, name='user2'),
    url(r'^htmlTest', views.htmlTest, name='htmlTest'),
    url(r'^csrf1', views.csrf1, name='csrf1'),
    url(r'csrf2', views.csrf2, name='csrf2'),
    url(r'^verifyCodes$', views.verifyCode),
    url(r'^verifyTest$', views.verifyCode),

]

test4/test4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('booktest.urls', namespace='booktest')),
]

test4/booktest/models.py
from django.db import models

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(db_column='pub_date')
    bread = models.IntegerField()
    bcommet = models.IntegerField()
    isDelet = models.BooleanField()
    class Meta():
        db_table = 'bookinfo'

class HeroInfo(models.Model):
    hname = models.CharField(max_length=10)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=1000)
    isDelet = models.BooleanField()
    book = models.ForeignKey('BookInfo')
    def showname(self):
        return self.hname

test4/booktest/views.py
#coding:utf-8
from django.shortcuts import render, HttpResponse
from models import *

def index(request):
    # hero = HeroInfo.objects.get(pk=1)
    # context = {'hero':hero}
    list = HeroInfo.objects.filter(isDelet=False)
    context = {'list':list}
    return render(request, 'booktest/index.html', context)

def show(request, id, id2):
    context = {'id':id}
    return render(request,'booktest/show.html', context)

#练习模板的继承
def index2(request):
    return render(request, 'booktest/index2.html')

def user1(request):
    context = {'uanme':'习总'}
    return render(request, 'booktest/user1.html', context)

def user2(request):
    return render(request, 'booktest/user2.html')

#html转义

def htmlTest(request):
    context = {'t1':'<h1>123<h1>'}
    return render(request, 'booktest/htmlTest.html', context)

#csrf
def csrf1(request):
    return render(request, 'booktest/csrf1.html')

def csrf2(request):
    uname = request.POST['uname']
    context = {'uname':uname}
    return render(request, 'booktest/csrf2.html', context)
#验证码

def verifyCode(request):
    from PIL import Image, ImageDraw, ImageFont
    import random
    #创建背景色
    bgColor = (random.randrange(50, 100), random.randrange(50, 100), 0)
    #规定宽高
    width = 100
    height = 26
    #创建画布
    image = Image.new('RGB', (width, height), bgColor)
    #构造字体对象
    font = ImageFont.truetype('/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMoBd.ttf', 25)
    #创建画笔
    draw = ImageDraw.Draw(image)
    #穿件文本内容
    text = '0123ABCD'
    #逐个绘制字符
    textTemp = ''
    for i in range(4):
        textTemp1 = text[random.randrange(0, len(text))]
        textTemp+=textTemp1
        draw.text(
            (i*25, 0),
            textTemp1,
            (255, 255, 255),
            font
        )

    request.session['code'] = textTemp
    # draw.text((0,0), text, (255,255,255), font)
    #保持到内存流中
    import cStringIO
    buf = cStringIO.StringIO()
    image.save(buf,'png')
    #将内存流中的内容输出到客户端
    return HttpResponse(buf.getvalue(), 'image/png')

def vervifyTest(request):
    return render(request, 'booktest/vervifyTest.html')

test4/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block head %} {%endblock%}
</head>
<body>
logo
<hr>
{% block content1 %}
    <h1>abc</h1>
{% endblock %}
<hr>
<h1>contact</h1>
</body>
</html>

test4/templates/booktest/base_goods.html
{% extends 'booktest/base.html' %}

test4/templates/booktest/base_user.html
{% extends 'booktest/base.html' %}
{% block content1 %}
<table border="1">
    <tr>
        <td height="300">用户导航</td>
        <td>{% block user_content %}{% endblock user_content %}</td>
    </tr>
</table>
{% endblock content1 %}

test4/templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="csrf2" method="post">
    {% csrf_token %}
    <input type="text" name="uname">
    <input type="submit" value="提交">
</form>
</body>
</html>

test4/templates/booktest/csrf2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ uname }}
</body>
</html>

test4/templates/booktest/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ t1|safe }}
<hr>
{% autoescape on %}
{{ t1 }}
{% endautoescape %}
</body>
</html>

test4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--{{ hero.showname }}-->
<a href="{% url 'booktest:show' '456' '789' %}">展示</a>
<hr>
<ul>
{% for hero in list %}
    {% if forloop.counter|divisibleby:"2" %}{# 求余过滤器 #}
        <li style="color: red">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% else %}
        <li style="color: blue" ">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% endif %}
    {% empty %}
    <li>啥也没找到</li>

{% endfor %}

</ul>
</body>
</html>

test4/templates/booktest/index2.html
{% extends 'booktest/base.html' %}

{% block content1 %}
<h1>123</h1>
{% endblock content1 %}

test4/templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ id }}
</body>
</html>

test4/templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}

{% block user_content %}

{% endblock user_content %}

test4/templates/booktest/user2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>